### ISSUE TITLE
Hardcoded Access token?

### ISSUE THREAD

**Issue by msurguy** [ubilabs/axidraw#59]
Thank you so much for this repo, it is really well made and usable as is! 

I was wondering if you meant to remove the access tokens from the `src` folder and replace with the tokens that come from config, specifically in these two locations:
https://github.com/ubilabs/axidraw/blob/bcaaf5c004ca55b9a6b1ddd4dc8a1797218e3c0b/src/draw-map.js#L3
https://github.com/ubilabs/axidraw/blob/bcaaf5c004ca55b9a6b1ddd4dc8a1797218e3c0b/src/draw-terrain.js#L48

Thank you!

**Comment by aemkei** [comment]
Thanks for checking this out! 

Guess @TheAmazingPT can take care of this as he already refactored most of the access tokens in #55.
